name: deploy kube-prometheus to cluster

on:
  push:
    branches:
      - main
    paths:
      - 'kube-prometheus-release-0.13/**'

jobs:
  deploy:
    name: Deploy kube-prometheus to cluster
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply --server-side -f ./kube-prometheus-release-0.13/manifests/setup

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply --server-side -f ./kube-prometheus-release-0.13/manifests/setup

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./kube-prometheus-release-0.13/manifests/
