name: "App deploy APP CI/CD"

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy app to cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, and push image to Yandex Cloud Container Registry
        if: github.event_name == 'push' && github.ref_type != 'tag'
        env:
          CR_REGISTRY: crp8096sp0do2c2hve0m
          CR_REPOSITORY: nginx-netology
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY ./app/docker/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        if: github.ref_type == 'tag'
        env:
          CR_REGISTRY: crp8096sp0do2c2hve0m
          CR_REPOSITORY: nginx-netology
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./app/docker/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Prepare deployment
        if: github.ref_type == 'tag'
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          cat ./app/deployment/app-deployment.yaml | sed "s/latest/$IMAGE_TAG/"

      - name: Deploy app
        if: github.ref_type == 'tag'
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./app/deployment/ -n app
          
            
